services:
  task-management:
    build:
      context: .
    environment:
      NODE_ENV: production
    env_file: '.env'
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - api-network

  db:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_DB: ${DB_NAME:-taskmanagement}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-your-secure-password}
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_NAME:-taskmanagement}',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - api-network

networks:
  api-network:
